# Problem 1

In [1]:
import numpy as np

In [2]:
n = int(input())

4


In [5]:
arr = np.array(range(1,n+1))
arr

array([1, 2, 3, 4])

In [10]:
matrix_1 = np.column_stack([arr**(n-i-1) for i in range(n)])
matrix_1

array([[ 1,  1,  1,  1],
       [ 8,  4,  2,  1],
       [27,  9,  3,  1],
       [64, 16,  4,  1]], dtype=int32)

In [13]:
# using vander function
matrix_2 = np.vander(arr,n,increasing=False)
matrix_2

array([[ 1,  1,  1,  1],
       [ 8,  4,  2,  1],
       [27,  9,  3,  1],
       [64, 16,  4,  1]])

# Problem 2

In [40]:
def moving_avg(test,k):
    res = np.cumsum(test)
#     print(res)
    l = []
    for i in range(len(test)-k+1):
        x = res[i+2]-sum(test[:i])
        l.append(x/3)
    return np.array(l)
test = [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
moving_avg(test,3)

array([  5.        ,   4.66666667,   5.66666667,   6.66666667,
         9.66666667,  28.66666667,  49.33333333,  72.66666667,
        84.        ,  93.33333333, 116.33333333])

In [19]:
def moving_avg(test,k):
    res = np.cumsum(test)
    res[k:] = res[k:]-res[:-k]
    return res[k-1 :]/k
test = [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
moving_avg(test,3)

array([  5.        ,   4.66666667,   5.66666667,   6.66666667,
         9.66666667,  28.66666667,  49.33333333,  72.66666667,
        84.        ,  93.33333333, 116.33333333])